### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by thresholdd** [Steve0212a/WpfCronExpressionUI#1]
The vertical alignment is inconsistent, particularly on the radio button controls.

**Comment by thresholdd** [comment]
I'm happy to contribute updates, let me know if your still actively maintaining this project.

**Comment by Steve0212a** [comment]
I have not made any changes to this in a while as we no longer use it in my main job/project.  However, I absolutely open to continuing it.  If you would like to contribute, I am open to that as well.
