### ISSUE TITLE
Control enabling

### ISSUE THREAD

**Issue by thresholdd** [Steve0212a/WpfCronExpressionUI#2]
When a radio button is not selected, can the associated controls be disabled.

**Comment by thresholdd** [comment]
I'm happy to contribute updates, let me know if your still actively maintaining this project.

**Comment by Steve0212a** [comment]
I have not made any changes to this in a while as we no longer use it in my main job/project.  However, I absolutely open to continuing it.  If you would like to contribute, I am open to that as well.

**Comment by thresholdd** [comment]
Hi Steve, both issues are resolved, do you mind publishing to NuGet. Cheers.

**Comment by Steve0212a** [comment]
will do - probably won't be until Monday. thx

**Comment by thresholdd** [comment]
Hi, would you prefer I publish to NuGet? Does the package need credentials? Thanks

**Comment by Steve0212a** [comment]
My apologies.  Super swamped coming back from a vacation.  Send me your user id from nuget.org and I will give you permission to publish.

Thanks!

**Comment by thresholdd** [comment]
Thanks. nuget user id is robertj3

**Comment by Steve0212a** [comment]
invitation sent
